import random

mapData = {
    "ardabil": 0,
    "isfahan": 20,
    "alborz": 11,
    "ilam": 18,
    "eastAzerbaijan": 10,
    "westAzerbaijan": 20,
    "bushehr": 15,
    "tehran": 3,
    "chaharmahalandBakhtiari": 25,
    "southKhorasan": 29,
    "razaviKhorasan": 11,
    "northKhorasan": 19,
    "khuzestan": 12,
    "zanjan": 18,
    "semnan": 9,
    "sistanAndBaluchestan": 3,
    "fars": 7,
    "qazvin": 35,
    "qom": 30,
    "kurdistan": 24,
    "kerman": 23,
    "kohgiluyehAndBoyerAhmad": 2,
    "kermanshah": 7,
    "golestan": 18,
    "gilan": 14,
    "lorestan": 7,
    "mazandaran": 28,
    "markazi": 25,
    "hormozgan": 14,
    "hamadan": 19,
    "yazd": 32,
}


def random_number():
    return random.randint(1, 30)


default_city_data = {
    "ardabil": {"germi": 9, "parsabad": 12, "bilehsavar": 3, "meshginshahr": 26, "namin": 17, "ardabil": 16,
                "sareyn": 6,
                "nir": 1, "khalkhal": 17, "kowsar": 28},
    "isfahan": {"khurandbiabanak": 15, "nain": 7, "ardestan": 23, "aranandbidgol": 5, "kashan": 15, "natanz": 16,
                "isfahan": 13, "borkhar": 20, "najafabad": 20, "mobarakeh": 9, "shahreza": 27, "dehaqan": 4,
                "semirom": 25,
                "fereydunshahr": 1, "chadegan": 11, "faridan": 4, "lenjan": 26, "tiranandkarvan": 7,
                "buinandmiandasht": 11, "khansar": 15, "golpayegan": 3, "shahinshahrandmeymeh": 13, "khomeynishahr": 22,
                "falavarjan": 13},
    "alborz": {"taleqan": 23, "karaj": 2, "savojbolagh": 6, "nazarabad": 15, "eshtehard": 4, "fardis": 9},
    "bushehr": {"deylam": 14, "ganaveh": 12, "dashtestan": 11, "bushehr": 16, "tangestan": 16, "dashti": 18, "deyr": 14,
                "asaluyeh": 15, "jam": 21, "kangan": 3},
    "chaharmahalandBakhtiari": {"kuhrang": 2, "ardal": 5, "lordegan": 25, "kiar": 11, "borujen": 20, "farsan": 17,
                                "shahrekord": 12, "saman": 18, "ben": 15},
    "eastAzerbaijan": {"charuymaq": 9, "maragheh": 24, "hashtrud": 21, "malekan": 18, "bonab": 14, "ajabshir": 18,
                       "mianeh": 26, "sarab": 9, "bostanabad": 8, "heris": 6, "osku": 9, "azarshahr": 22, "tabriz": 2,
                       "shabestar": 14, "varzaqan": 20, "maarand": 16, "jolfa": 3, "khodaafarin": 9, "ahar": 21,
                       "kaleybar": 12},
    "fars": {"larestan": 27, "darab": 22, "zarindasht": 16, "neyriz": 27, "bavanat": 17, "estahban": 27, "fasa": 17,
             "jahrom": 10, "lamerd": 12, "gerash": 2, "khonj": 20, "mohr": 25, "qirandkarzin": 2, "farashband": 29,
             "firuzabad": 12, "kavar": 23, "sarvestan": 15, "kharameh": 10, "shiraz": 28, "kazerun": 26, "arsanjan": 27,
             "khorambid": 19, "abadeh": 3, "eqlid": 24, "rostam": 26, "mamasani": 17, "marvdasht": 17, "ardakan": 19,
             "pasargad": 4},
    "gilan": {"astara": 29, "talesh": 17, "rezvanshahr": 13, "masal": 8, "bandaranzali": 29, "sowmeehsara": 28,
              "fuman": 26, "shaft": 22, "rasht": 17, "rudbar": 3, "siahkal": 12, "astanehyeashrafiyeh": 17,
              "lahijan": 7,
              "langarud": 22, "rudsar": 18, "amlash": 29},
    "golestan": {"maravehtapeh": 9, "kalaleh": 24, "galikash": 12, "minudasht": 21, "azadshahr": 7, "ramian": 19,
                 "aliabad": 1, "gorgan": 16, "kordkuy": 8, "bandaregaz": 5, "torkaman": 26, "gomishan": 13, "aqqala": 3,
                 "gonbadekavus": 19},
    "hamadan": {"malayer": 19, "nahavand": 21, "tuyserkan": 7, "asadabad": 8, "bahar": 2, "hamadan": 16, "famenin": 18,
                "razan": 1, "kabudarahang": 25},
    "hormozgan": {"parsian": 29, "bandarlengeh": 22, "bastak": 14, "khamir": 10, "bandarabas": 6, "hajiabad": 9,
                  "rudan": 15, "minab": 4, "sirik": 17, "jask": 3, "qeshm": 28, "bashagard": 2},
    "ilam": {"dehloran": 6, "mehran": 17, "malekshahi": 18, "darehshahr": 27, "badreh": 12, "eyvan": 6, "ilam": 13,
             "chardavol": 21},
    "kerman": {"qalehganj": 5, "rudbarejonub": 18, "rigan": 10, "fahraj": 1, "manujan": 19, "kahnuj": 15,
               "anbarabad": 17,
               "faryab": 17, "bam": 25, "narmashir": 12, "kerman": 18, "jiroft": 5, "arzuiyeh": 5, "baft": 12,
               "rabor": 14,
               "bardsir": 17, "ravar": 20, "kuhbanan": 2, "zarand": 26, "rafsanjan": 19, "sirjan": 26, "anar": 22,
               "shahrebabak": 14},
    "kermanshah": {"gilanegharb": 27, "ghasreshirin": 18, "eslamabadegharb": 12, "kermanshah": 28, "harsin": 12,
                   "kangavar": 12, "sahneh": 3, "songhor": 14, "ravansar": 29, "paveh": 21, "javanrud": 25, "dalahu": 2,
                   "salasebabajani": 27, "sarpolezahab": 6},
    "khuzestan": {"andimeshk": 8, "dezful": 21, "shush": 1, "dashteazadegan": 29, "hoveyzeh": 29, "gotvand": 18,
                  "lali": 21, "andika": 16, "izeh": 1, "masjedsoleyman": 9, "shushtar": 14, "hamidiyeh": 13, "ahvaz": 6,
                  "bavi": 9, "haftkel": 12, "baghemalek": 28, "ramhormoz": 25, "ramshir": 27, "aghajari": 7,
                  "bandaremahshahr": 14, "behbahan": 13, "hendijan": 26, "omidiyeh": 16, "karun": 8, "khoramshahr": 23,
                  "abadan": 14, "shadegan": 25},
    "kohgiluyehAndBoyerAhmad": {"gachsaran": 5, "basht": 9, "choram": 8, "boyerahmad": 10, "dana": 26, "kohgiluyeh": 4,
                                "landeh": 6, "bahmai": 2},
    "kurdistan": {"ghorveh": 16, "dehgolan": 4, "kamyaran": 13, "sanandaj": 3, "sarvabad": 18, "marivan": 3,
                  "bijar": 17,
                  "divandareh": 22, "saghez": 8, "baneh": 14},
    "lorestan": {"aligudarz": 16, "azna": 11, "dorud": 1, "borujerd": 23, "khoramabad": 19, "selseleh": 4, "delfan": 17,
                 "poldokhtar": 18, "dowreh": 29, "rumeshkan": 9, "kuhdasht": 26},
    "markazi": {"zarandieh": 5, "saveh": 24, "tafresh": 22, "komijan": 5, "khondab": 12, "shazand": 25, "khomeyn": 22,
                "mahalat": 4, "delijan": 1, "ashtian": 14, "farahan": 19, "arak": 24},
    "mazandaran": {"galugah": 3, "behshahr": 2, "neka": 2, "miandorud": 20, "sari": 5, "savadkuh": 27,
                   "northsavadkuh": 8,
                   "ghaemshahr": 15, "juybar": 21, "simorgh": 1, "babolsar": 22, "babol": 26, "amol": 1, "nur": 16,
                   "noshahr": 7, "chalus": 25, "kelardasht": 8, "abasabad": 19, "tonekabon": 14, "ramsar": 12,
                   "fereydunkenar": 15, "mahmudabad": 14},
    "northKhorasan": {"esfarayn": 22, "faruj": 9, "shirvan": 9, "bojnord": 4, "jajarm": 24, "garmeh": 8,
                      "manehandsamalqan": 23, "razandjargalan": 12},
    "qazvin": {"buinzahra": 6, "avaj": 28, "takestan": 19, "abyek": 5, "alborz": 13, "qazvin": 9}, "qom": {"qom": 29},
    "razaviKhorasan": {"dargaz": 9, "quchan": 16, "neyshabur": 20, "chenaran": 9, "binalud": 27, "mashhad": 23,
                       "khoshab": 4, "firuzeh": 1, "jowayin": 22, "davarzan": 18, "joghatai": 6, "sabzevar": 25,
                       "kalat": 19, "sarakhs": 2, "fariman": 25, "bardaskan": 17, "bajestan": 28, "kashmar": 19,
                       "gonabad": 12, "torbatejam": 22, "torbateheydarieh": 23, "zaveh": 1, "roshtkhar": 21,
                       "bakhraz": 4,
                       "khvaf": 6, "taybad": 25, "mahvelat": 15, "khalilabad": 23},
    "semnan": {"shahrud": 2, "damghan": 20, "semnan": 13, "sorkheh": 24, "aradan": 14, "garmsar": 10, "meyami": 19,
               "mehdishahr": 4},
    "sistanAndBaluchestan": {"hirmand": 6, "zahak": 26, "nimruz": 25, "hamun": 26, "zabol": 10, "zahedan": 17,
                             "mirjaveh": 5, "khash": 16, "iranshahr": 16, "saravan": 6, "mehrestan": 6, "dalgan": 19,
                             "sibandsuran": 8, "sarbaz": 10, "fanuj": 25, "nikshahr": 19, "chabahar": 5, "konarak": 22,
                             "qasreqand": 15},
    "southKhorasan": {"nehbandan": 15, "sarbisheh": 5, "darmian": 9, "zirkuh": 2, "qaenat": 3, "birjand": 27,
                      "khusf": 4,
                      "tabas": 7, "sarayan": 5, "ferdows": 29, "boshruyeh": 15},
    "tehran": {"malard": 24, "shahriar": 27, "robatkarim": 29, "baharestan": 12, "eslamshahr": 11, "qods": 21,
               "tehran": 4,
               "rey": 5, "varamin": 27, "pishva": 1, "qarchak": 15, "pakdasht": 1, "damavand": 12, "pardis": 13,
               "shemiranat": 7, "firuzkuh": 24},
    "westAzerbaijan": {"maku": 10, "chaldoran": 5, "showt": 1, "poldasht": 10, "chaypareh": 16, "khoy": 28,
                       "salmas": 21,
                       "urmia": 24, "naqadeh": 25, "oshnavieh": 12, "piranshahr": 13, "sardasht": 13, "mahabad": 24,
                       "bukan": 5, "shahindezh": 15, "takab": 2, "miandoab": 4},
    "yazd": {"khatam": 20, "mehriz": 21, "taft": 1, "abarkuh": 11, "bafq": 19, "yazd": 23, "ashkezar": 2, "meybod": 20,
             "ardakan": 22, "behabad": 26},
    "zanjan": {"tarom": 20, "zanjan": 22, "mahneshan": 15, "ijrud": 1, "soltaniyeh": 3, "abhar": 29, "khodabandeh": 14,
               "khoramdareh": 23}}

default_province_data = {}

for p, city_dict in default_city_data.items():
    default_province_data[p] = sum(city_dict.values())
